[package]
name = "codetools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ct"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tree-sitter = "0.22"
tree-sitter-rust = "0.21"

[dev-dependencies]
assert_matches = "1.5"
